### ISSUE TITLE
Error Traceback for Cryptopia Exchange

### ISSUE THREAD

**Issue by RGAlexander216** [CryptoSignal/crypto-signal#196]
This is somewhat of an FYI, I may be able to implement a workaround. If so I'll let you know, but if you beat me to it then that's fine too.
-------------------------------
Beginning analysis of cryptopia
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 41, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 56, in run
    self.__test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 85, in __test_strategies
    candle_period
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/app/exchange.py", line 59, in get_historical_data
    if time_unit not in self.exchanges[exchange].timeframes:
AttributeError: 'cryptopia' object has no attribute 'timeframes'

**Comment by RGAlexander216** [comment]
This was actually my own fault, closing.
