### ISSUE TITLE
ValueError causes main to stop loop with bad data in frame

### ISSUE THREAD

**Issue by rhamnett** [CryptoSignal/crypto-signal#201]
Traceback (most recent call last):
  File "app.py", line 109, in <module>
    main()
  File "app.py", line 46, in main
    behaviour.run(settings['market_pairs'])
  File "/app/behaviour.py", line 59, in run
    self.__test_strategies(market_data)
  File "/app/behaviour.py", line 101, in __test_strategies
    period_count=period_count
  File "/app/indicators/rsi.py", line 33, in analyze
    dataframe = self.convert_to_dataframe(historical_data)
  File "/app/indicators/utils.py", line 27, in convert_to_dataframe
    dataframe.columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume']
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3627, in _setattr_
    return object._setattr_(self, name, value)
  File "pandas/libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.set_
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 559, in _set_axis
    self._data.set_axis(axis, labels)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3069, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 6 elements

**Comment by shads2** [comment]
Are you using the latest version? A fix was implemented for this problem last week

**Comment by rhamnett** [comment]
Thanks for the reply. I thought so but perhaps not. I shall reset the branch and open again if further issues. Cheers

**Comment by shads2** [comment]
Thanks, more than happy to look into it again if the issue still persists.

**Comment by rhamnett** [comment]
This was my mistake
