### ISSUE TITLE
Json output mode is not working

### ISSUE THREAD

**Issue by hslimi** [CryptoSignal/crypto-signal#222]
It's working normally without output config, but when i switch the output to `json`I get this error: 
```
Using the following exchange(s): ['binance']
Beginning analysis of binance
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 41, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 56, in run
    self.__test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 148, in __test_strategies
    output = self.__get_json_output(analyzed_data, market_pair)
  File "/app/behaviour.py", line 285, in __get_json_output
    stringified_analysis[analysis]['is_hot'] = str(analyzed_data[analysis]['is_hot'])
TypeError: list indices must be integers or slices, not str
```

**Comment by jrbartola** [comment]
cc94593
