### ISSUE TITLE
telegram throws error if message is empty

### ISSUE THREAD

**Issue by tommuhm** [CryptoSignal/crypto-signal#227]
**Exception:** telegram.error.BadRequest: Message must be non-empty

**Full Traceback:**
```
app_1  | Traceback (most recent call last):
app_1  |   File "app.py", line 46, in <module>
app_1  |     main()
app_1  |   File "app.py", line 41, in main
app_1  |     behaviour.run(settings['market_pairs'], settings['output_mode'])
app_1  |   File "/app/behaviour.py", line 56, in run
app_1  |     self.__test_strategies(market_data, output_mode)
app_1  |   File "/app/behaviour.py", line 155, in __test_strategies
app_1  |     self.notifier.notify_all(message)
app_1  |   File "/app/notification.py", line 101, in notify_all
app_1  |     self.notify_telegram(message)
app_1  |   File "/app/notification.py", line 156, in notify_telegram
app_1  |     self.telegram_client.notify(message)
app_1  |   File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
app_1  |     return self.call(f, *args, **kw)
app_1  |   File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
app_1  |     start_time=start_time)
app_1  |   File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 252, in iter
app_1  |     return fut.result()
app_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
app_1  |     return self.__get_result()
app_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
app_1  |     raise self._exception
app_1  |   File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
app_1  |     result = fn(*args, **kwargs)
app_1  |   File "/app/notifiers/telegram_client.py", line 46, in notify
app_1  |     self.bot.send_message(chat_id=self.chat_id, text=message_chunk)
app_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
app_1  |     result = func(self, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
app_1  |     result = self._request.post(url, data, timeout=kwargs.get('timeout'))
app_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 273, in post
app_1  |     **urlopen_kwargs)
app_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 210, in _request_wrapper
app_1  |     raise BadRequest(message)
app_1  | telegram.error.BadRequest: Message must be non-empty
cryptosignal_app_1 exited with code 1
```

**Comment by shads2** [comment]
PR's merged :)

**Comment by shads2** [comment]
Hmm I thought the new message handler accounted for empty messages but evidently something isn't quite working right. I'll re-open this issue.

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/249 pending review.

**Comment by jrbartola** [comment]
Done
