### ISSUE TITLE
Crash when analyzing BTC/USD on bitmex

### ISSUE THREAD

**Issue by sputnik1458** [CryptoSignal/crypto-signal#321]
My config.yml is 
` settings:
    update_interval: 30
    market_pairs:
        - BTC/USD

exchanges:
    bitmex:
        required:
            enabled: true `

and the output is 
`enabled notifers: []
Starting default analyzer...
Found configured markets: ['BTC/USD']
Using the following exchange(s): ['bitmex']
Beginning analysis of bitmex
Beginning analysis of BTC/USD
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 89, in _test_strategies
    market_pair
  File "/app/behaviour.py", line 165, in _get_indicator_results
    market_pair
  File "/app/behaviour.py", line 328, in _get_analysis_result
    results = dispatcher[indicator](**dispatcher_args)
  File "/app/analyzers/indicators/mfi.py", line 33, in analyze
    mfi_values = abstract.MFI(dataframe, period_count).to_frame()
  File "talib/_abstract.pxi", line 352, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 383, in talib._ta_lib.Function.__call_function
  File "talib/_func.pxi", line 8454, in talib._ta_lib.MFI
Exception: volume is not double`

**Comment by maselko** [comment]
I see the same problem.

**Comment by Pei-ChunLee** [comment]
If you disable mfi & obv, it is working.
