### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by Atem18** [CryptoSignal/crypto-signal#351]
Hi @jrbartola ,

First, thanks for the program, it's awesome.

Second, do you know why I have that issue ?

```
REP/USD:

indicators:	rsi #0: 37.57571773 	bbp #0: 0.08632842/4.18769970
informants:
crossovers:


Is first run: True
Alert once for REP/USD rsi 30m
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "app.py", line 94, in run
    self.behaviour.run(self.market_data, self.settings['output_mode'])
  File "/app/behaviour.py", line 74, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 148, in notify_all
    self.notify_stdout(new_analysis)
  File "/app/notification.py", line 306, in notify_stdout
    self.notifier_config['stdout']['optional']['template']
  File "/app/notification.py", line 352, in _indicator_message_templater
    if analysis['result'].shape[0] == 0:
KeyError: 'result'
```
My config FYI :
```
settings:
  log_level: DEBUG
  update_interval: 60
  market_pairs:
    - REP/USD

exchanges:
  kraken:
    required:
      enabled: true

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - rsi
      hot: 50
      cold: 70
      candle_period: 30m
      period_count: 14
      mute_cold: true
  bbp:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      candle_period: 30m
      period_count: 20
      hot: 0.5
      cold: 1
      std_dev: 2
      signal:
        - bbp
        - mfi
      hot_label: 'Lower Band'
      cold_label: 'Upper Band'
      indicator_label: 'Bollinger Crossing'
      mute_cold: true

notifiers:
  stdout:
    required:
      enable: true
    optional:
      template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"
```

Thanks in advance

**Comment by laliux** [comment]
Hi,

Are u working with the develop branch ?

**Comment by Atem18** [comment]
Hi @laliux ,

Yes I am. Is it wrong ?

**Comment by laliux** [comment]
Is fine, .. seems a little bug with stdout notifier. I'm going to check it.

Btw, the most proven (and cool) notifier is Telegram. I recommend to use it.

**Comment by Atem18** [comment]
Ok thanks, I will have a look at it.

**Comment by laliux** [comment]
@Atem18 

Hi, 

I wrote a fix and is ready to test. Just pull the latest develop branch.

Best
