### ISSUE TITLE
Error with exchange Kraken

### ISSUE THREAD

**Issue by x1n5h3n** [CryptoSignal/crypto-signal#380]
I'm getting an erro when using kraken exchange:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 364, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/app/exchange.py", line 137, in get_exchange_markets
    exchange_markets[exchange] = self.exchanges[exchange].load_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 871, in load_markets
    markets = self.fetch_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 259, in fetch_markets
    limits = self.fetch_min_order_sizes()
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 239, in fetch_min_order_sizes
    raise e
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 234, in fetch_min_order_sizes
    html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 844, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 377, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 406, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: kraken https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- GET 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- <!DOCTYPE html>
```
[...]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 59, in run
    market_data = self.exchange_interface.get_exchange_markets(markets=market_pairs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 266, in iter
    six.raise_from(RetryError(fut), fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7fb881452160 state=finished raised ExchangeNotAvailable>]
```

I'm using `crypto-signal` with a testing `config.yml`:
```yml
settingsn old version ?
  log_level: DEBUG
  update_interval: 60
  market_pairs:
    - ADA/USD

exchanges:
  kraken:
    required:
      enabled: true
```

Is any one facing the same issue ? Is it a cctx error due to an old version ?

**Comment by x1n5h3n** [comment]
I'm using the master branch

**Comment by laliux** [comment]
Hey @x1n5h3n 

Yes, it was an issue with version of ccxt, moving to v1.25.40 seems to fix it.

To test it please switch to develop branch.

https://github.com/CryptoSignal/crypto-signal/blob/develop/README.md

Best

**Comment by x1n5h3n** [comment]
Thanks for your quick reply @laliux 
It's what I've done:
```bash
git clone https://github.com/CryptoSignal/crypto-signal.git
cd crypto-signal
git checkout develop
cp default-config.yml app/config.yml
```
I've got this in `config.yml`:

```yml
settings:
  update_interval: 300
  market_pairs:
    - ADA/ETH

exchanges:
  kraken:
    required:
      enabled: true
```

```bash
sudo docker build -t dev/crypto-signals:latest .
```
I've got this warning:
```
ARNING: You are using pip version 19.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Maybe because crypto-signal is using `pip` and not `pip3`.

```bash
sudo docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest
```

And got the same error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 493, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/app/exchange.py", line 179, in get_exchange_markets
    exchange_markets[exchange] = self.exchanges[exchange].load_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1079, in load_markets
    markets = self.fetch_markets(params)
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 274, in fetch_markets
    limits = self.fetch_min_order_amounts()
  File "/usr/local/lib/python3.6/site-packages/ccxt/kraken.py", line 252, in fetch_min_order_amounts
    html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 388, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 417, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 413, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 506, in fetch
    self.handle_rest_errors(e, response.status_code, http_response, url, method)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 531, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 398, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: kraken https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size- GET 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size- <!DOCTYPE html>
```

[...]

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 100, in <module>
    main()
  File "app.py", line 36, in main
    market_data = exchange_interface.get_exchange_markets(markets=market_pairs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 266, in iter
```
    six.raise_from(RetryError(fut), fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f4b92188dd8 state=finished raised ExchangeNotAvailable>]

**Comment by laliux** [comment]
Sorry @x1n5h3n , I can't reproduce the error. I did the process from scratch and its working fine.

....

WARNING: You are using pip version 19.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container e58f822c17df
 ---> 0a674e0b4a74
Step 9/9 : CMD ["/usr/local/bin/python","app.py"]
 ---> Running in ad8c79569b2d
Removing intermediate container ad8c79569b2d
 ---> b0994b52eb6c
Successfully built b0994b52eb6c
Successfully tagged dev/crypto-signals:latest

laliux@corsair:/tmp/crypto-signal(develop○) » docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest
Found configured markets: ['ADA/ETH']
enabled notifers: []
Starting Worker-1
Starting default analyzer...
Using the following exchange(s): ['kraken']
Getting data for ['ADA/ETH']
Beginning analysis of kraken
Beginning analysis of ADA/ETH
ADA/ETH:	

indicators:	momentum #0: 0.00004300 	mfi #0: 73.92858994 	obv #0: 23193050.56250977 	rsi #0: 71.51858439 	stoch_rsi #0: 0.00000000 	macd #0: 0.00004857 	ichimoku #0: 0.00031430/0.00028505 	iiv #0: 0.00000000 	
informants:	lrsi #0: 0.13873522 	lrsi #1: 0.93225337 	vwap #0: 0.00048694 	sma #0: 0.00049960 	ema #0: 0.00049809 	bollinger_bands #0: 0.00059490/0.00045636/0.00031782 	ohlcv #0: 0.00053510 	
crossovers:	


Worker-1 sleeping for 300 seconds

**Comment by laliux** [comment]
@x1n5h3n try this:

1. delete the build docker images
2. clone the repo again and checkout develop
3. confirm the ccxt version is ccxt==1.25.40 app/requirements-step-2.txt 
4. build the docker image again

Best

**Comment by x1n5h3n** [comment]
Thanks @laliux, it's working great !

**Comment by dkuci99** [comment]
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 59, in run
    market_data = self.exchange_interface.get_exchange_markets(markets=market_pairs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 266, in iter
    six.raise_from(RetryError(fut), fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f09c496f978 state=finished raised ExchangeNotAvailable>]

**Comment by 0x-Johnson** [comment]
I have received. Thanks.Johnson

**Comment by dkuci99** [comment]
Any help with my issue, I have updated the cctx as per your suggestion and rebuilt the docker image, but still I am getting the same error
