### ISSUE TITLE
Error in notifiers

### ISSUE THREAD

**Issue by tirouj** [CryptoSignal/Crypto-Signal#394]
Hello

I have tried both Telegram and Gmail and both with below errors. At the time of writing this I can't see the Telegram error but it doesn't do anything. If I see the error again I will update here
Please kindly advice:

Config file:

notifiers:
    gmail:
        required:
            username: xxxxx@gmail.com
            password: xxxx
            destination_emails:
                - xxxx@xxx.com
        optional:
            template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"

Error for gmail:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/app/notifiers/gmail_client.py", line 48, in notify
    smtp_handler = smtplib.SMTP(self.smtp_server)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 65, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 104, in notify_all
    self.notify_gmail(new_analysis)
  File "/app/notification.py", line 170, in notify_gmail
    self.gmail_client.notify(message)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 266, in iter
    six.raise_from(RetryError(fut), fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7fcc3ffcb780 state=finished raised OSError>]

**Comment by laliux** [comment]
Telegram is well supported, also discord and webhook. Gmail is no longer supported.

Be sure u are working with develop branch. https://github.com/CryptoSignal/Crypto-Signal/blob/develop/README.md

If u want share me your config file, then I can check.

Best

**Comment by laliux** [comment]
Closed due to no answer.
