### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by PetarKresimirCulina** [CryptoSignal/Crypto-Signal#415]
```
Beginning analysis of HSR/BTC
No historical data provided returned by exchange.
Invalid data encountered while processing pair HSR/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair HSR/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair HSR/BTC, skipping
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 98, in _test_strategies
    new_result[exchange][market_pair]
  File "/app/behaviour.py", line 250, in _get_crossover_results
    key_indicator = new_result[crossover_conf['key_indicator_type']][crossover_conf['key_indicator']][crossover_conf['key_indicator_index']]
IndexError: list index out of range
```

**Comment by laliux** [comment]
Hey @PetarKresimirCulina ,

What Exchange are u using?
What indicators/candle periods?
Are u working with code in develop branch?

**Comment by laliux** [comment]
Closed because no answer.
