### ISSUE TITLE
Crypto-Signal on Synology Nas ( Docker)

### ISSUE THREAD

**Issue by flamby69** [CryptoSignal/Crypto-Signal#435]
hi, 

i try to launch the docker file with the docker app of my synology nas, and it don't stop rebooting. Anyone try this config and know if we need to add variable parameter ?( i only add the yml file in /app/config.yml )

I check the log and get theses lines : 

 Traceback (most recent call last):

  File "app.py", line 45, in <module>

  main()

  File "app.py", line 30, in main

  notifier = Notifier(config.notifiers)

  File "/app/notification.py", line 48, in __init__

  avatar=notifier_config['discord']['optional']['avatar']

KeyError:  'avatar'

thanks by advance for your help.

**Comment by flamby69** [comment]
sorry, like the noob i am, i delete the avatar line instead of put "None" on it.. It seems to work now
