### ISSUE TITLE
working for binance but not for coinbase crypto patform. any changes required to support coinbase?

### ISSUE THREAD

**Issue by subbu52** [CryptoSignal/Crypto-Signal#455]
config.yml file:

settings:
  update_interval: 300
  market_pairs:
    - BTC/USDT
    - SHIB/USDT
    - DOGE/USDT

exchanges:
  coinbase:
    required:
      enabled: true

  binance:
    required:
      enabled: true

sudo docker run --rm -v ~/Crypto-Signal/config.yml:/app/config.yml shadowreaver/crypto-signal:master
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 29, in main
    exchange_interface = ExchangeInterface(config.exchanges)
  File "/app/exchange.py", line 30, in __init__
    new_exchange = getattr(ccxt, exchange)({
AttributeError: module 'ccxt' has no attribute 'coinbase'

**Comment by w1ld3r** [comment]
@subbu52, you probably want Coinbase Pro. Coinbase is not an exchange, it's a wallet service with some rich functions. Can you try replacing coinbase by coinbasepro ?

**Comment by w1ld3r** [comment]
I think it's onlu available with cctx pro: https://packagist.org/packages/ccxt/ccxt
