### ISSUE TITLE
telegram.utils  of  develop  branche

### ISSUE THREAD

**Issue by qq020608** [CryptoSignal/Crypto-Signal#472]
i can use the master branche , and i want to try some other features of the devekop branche , but i got always this error  , and  i have tried   "pip install telegram"  and  "pip install python-telegram-bot" , it doesn't help , and even i del telegram in my config.yml , i got still this error , my system is  ubuntu-22.04.2-desktop-amd64 , so what should  i do ?

test@test-virtual-machine:~/crypto-signal$ sudo docker run --rm -ti -v  $PWD/app:/app dev/crypto-signals:latest
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    from notification import Notifier
  File "/app/notification.py", line 35, in <module>
    from notifiers.telegram_client import TelegramNotifier
  File "/app/notifiers/telegram_client.py", line 8, in <module>
    from telegram.utils.request import Request
ModuleNotFoundError: No module named 'telegram.utils'

**Comment by onradr** [comment]
same problem

**Comment by laliux** [comment]
@onradr @qq020608 temporal fix, set **python-telegram-bot==13.13** in app/requirements-step-2.txt file.

**Comment by alkhachatryan** [comment]
> @onradr @qq020608 temporal fix, set **python-telegram-bot==13.13** in app/requirements-step-2.txt file.

I have another error because of that:

```
app_1  | Traceback (most recent call last):
app_1  |   File "/app/app.py", line 17, in <module>
app_1  |     from notification import Notifier
app_1  |   File "/app/notification.py", line 27, in <module>
app_1  |     from telegram.error import TimedOut as TelegramTimedOut
app_1  |   File "/usr/local/lib/python3.12/site-packages/telegram/__init__.py", line 186, in <module>
app_1  |     from .bot import Bot
app_1  |   File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 106, in <module>
app_1  |     from telegram.utils.request import Request
app_1  |   File "/usr/local/lib/python3.12/site-packages/telegram/utils/request.py", line 44, in <module>
app_1  |     import urllib3.contrib.appengine as appengine  # type: ignore[no-redef]
app_1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1  | ModuleNotFoundError: No module named 'urllib3.contrib.appengine'

```

**Comment by alkhachatryan** [comment]
All you need to do is to remove the second argument when creating a bot client.
In __init__ of TelegramNotifier just have this, instead of creation with Request argument:

`self.bot = telegram.Bot(token=token)`

And you can install the latest version of telegram client

**Comment by laliux** [comment]
@alkhachatryan yes, by doing that change, the latest version of python-telegram-bot (e.g 20.8) can be installed.

But, v20.x is a breaking version because it is built on top of  asyncio module, and a lot of changes in app are required. In my opinion, it's not worth it. That's why I'm gonna freeze with 13.x version.

**Comment by alkhachatryan** [comment]
@laliux all required changes to telegram with asyncio ARE fixed in my repo:
https://github.com/krypt0ra/station
And now telegram notifier works like a charm.

**Comment by 0x-Johnson** [comment]
I have received. Thanks.Johnson

**Comment by fragrantauto** [comment]
It looks like you are encountering a `ModuleNotFoundError` for `telegram.utils`, which suggests that the version of `python-telegram-bot` you are using might not be compatible with the code in your app. If you're trying to use features from the develop branch, ensure that you're using the compatible version that offers the `telegram.utils.request` module. You might want to check the commit history or documentation in the develop branch for any changes related to the Telegram API and see if there are any specific instructions for setting up the environment for development. Additionally, have you confirmed that your Docker image is pulling the latest code from the develop branch correctly?

**Comment by naeemgwendlyn26** [comment]
Since `python-telegram-bot` v20+ removed `telegram.utils.request`, you must either pin `python-telegram-bot<20.0` in your requirements or refactor `notifiers/telegram_client.py` to handle the asynchronous implementation required by the newer library versions.
